// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface LegalRequestRecord {
    request_type?: string;
    jurisdiction?: string;
    authority?: string;
    scope?: string;
    notes?: string;
}
