// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         request_id: "request_id"
 *     }
 */
export interface RespondToLegalRequestTransparencyRequest {
    request_id: string;
    complied?: boolean;
    challenged?: boolean;
    notes?: string;
}
