// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         host_id: "host_id",
 *         job_id: "job_id"
 *     }
 */
export interface ApiSchedulePreemptionAgentPreemptHostIdJobIdPostRequest {
    host_id: string;
    job_id: string;
}
