// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         token: "token",
 *         new_password: "new_password"
 *     }
 */
export interface PasswordResetConfirm {
    token: string;
    new_password: string;
}
