// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         token_prefix: "token_prefix"
 *     }
 */
export interface RevokeSessionAuthRequest {
    token_prefix: string;
}
