// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         entity_id: "entity_id"
 *     }
 */
export interface ApiReputationBreakdownApiReputationEntityIdBreakdownGetRequest {
    entity_id: string;
}
