// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         message: "message"
 *     }
 */
export interface AiChatRequest {
    message: string;
    conversation_id?: string | null;
    page_context?: string;
}
