// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as XcelsiorApi from "../../../index.js";

export declare namespace AuthClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AuthClient {
    protected readonly _options: NormalizedClientOptions<AuthClient.Options>;

    constructor(options: AuthClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Register a new user with email and password.
     *
     * Creates an account and returns a session token for immediate use.
     * Password is hashed with PBKDF2-HMAC-SHA256 + random 16-byte salt.
     *
     * @param {XcelsiorApi.RegisterRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.auth.apiAuthRegister({
     *         email: "email",
     *         password: "password"
     *     })
     */
    public apiAuthRegister(
        request: XcelsiorApi.RegisterRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiAuthRegister(request, requestOptions));
    }

    private async __apiAuthRegister(
        request: XcelsiorApi.RegisterRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/auth/register",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/auth/register");
    }

    /**
     * Authenticate with email and password.
     *
     * Returns a Bearer token valid for 30 days.
     *
     * @param {XcelsiorApi.LoginRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.auth.apiAuthLogin({
     *         email: "email",
     *         password: "password"
     *     })
     */
    public apiAuthLogin(
        request: XcelsiorApi.LoginRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiAuthLogin(request, requestOptions));
    }

    private async __apiAuthLogin(
        request: XcelsiorApi.LoginRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/auth/login",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/auth/login");
    }

    /**
     * Initiate OAuth flow — returns the provider's authorization URL.
     *
     * The frontend should redirect the user to the returned URL.
     *
     * @param {XcelsiorApi.ApiAuthOauthInitiateApiAuthOauthProviderPostRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.auth.apiAuthOauthInitiate({
     *         provider: "provider"
     *     })
     */
    public apiAuthOauthInitiate(
        request: XcelsiorApi.ApiAuthOauthInitiateApiAuthOauthProviderPostRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiAuthOauthInitiate(request, requestOptions));
    }

    private async __apiAuthOauthInitiate(
        request: XcelsiorApi.ApiAuthOauthInitiateApiAuthOauthProviderPostRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { provider } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/auth/oauth/${core.url.encodePathParam(provider)}`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/auth/oauth/{provider}");
    }

    /**
     * OAuth callback — exchanges authorization code for user profile, creates session,
     * and redirects to dashboard.
     *
     * @param {XcelsiorApi.ApiAuthOauthCallbackApiAuthOauthProviderCallbackGetRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.auth.apiAuthOauthCallback({
     *         provider: "provider"
     *     })
     */
    public apiAuthOauthCallback(
        request: XcelsiorApi.ApiAuthOauthCallbackApiAuthOauthProviderCallbackGetRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiAuthOauthCallback(request, requestOptions));
    }

    private async __apiAuthOauthCallback(
        request: XcelsiorApi.ApiAuthOauthCallbackApiAuthOauthProviderCallbackGetRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { provider } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/auth/oauth/${core.url.encodePathParam(provider)}/callback`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/auth/oauth/{provider}/callback",
        );
    }

    /**
     * Get the currently authenticated user's profile.
     *
     * Requires Authorization: Bearer <token> header.
     *
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.auth.apiAuthMe()
     */
    public apiAuthMe(requestOptions?: AuthClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiAuthMe(requestOptions));
    }

    private async __apiAuthMe(requestOptions?: AuthClient.RequestOptions): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/auth/me",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.XcelsiorApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/auth/me");
    }

    /**
     * Delete the current user's account.
     *
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.auth.apiAuthDeleteAccount()
     */
    public apiAuthDeleteAccount(requestOptions?: AuthClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiAuthDeleteAccount(requestOptions));
    }

    private async __apiAuthDeleteAccount(
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/auth/me",
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.XcelsiorApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/api/auth/me");
    }

    /**
     * Update the current user's profile fields.
     *
     * @param {XcelsiorApi.ProfileUpdateRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.auth.apiAuthUpdateProfile()
     */
    public apiAuthUpdateProfile(
        request: XcelsiorApi.ProfileUpdateRequest = {},
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiAuthUpdateProfile(request, requestOptions));
    }

    private async __apiAuthUpdateProfile(
        request: XcelsiorApi.ProfileUpdateRequest = {},
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/auth/me",
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/api/auth/me");
    }

    /**
     * Refresh an existing session token.
     *
     * Returns a new token with a fresh 30-day expiry.
     *
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.auth.apiAuthRefresh()
     */
    public apiAuthRefresh(requestOptions?: AuthClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiAuthRefresh(requestOptions));
    }

    private async __apiAuthRefresh(requestOptions?: AuthClient.RequestOptions): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/auth/refresh",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.XcelsiorApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/auth/refresh");
    }

    /**
     * Generate a named API key for the authenticated user.
     *
     * API keys can be used as Bearer tokens for programmatic access.
     * Scope: 'full-access' (default) or 'read-only' (GET requests only).
     *
     * @param {XcelsiorApi.ApiGenerateApiKeyApiKeysGeneratePostRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.auth.apiGenerateApiKey()
     */
    public apiGenerateApiKey(
        request: XcelsiorApi.ApiGenerateApiKeyApiKeysGeneratePostRequest = {},
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiGenerateApiKey(request, requestOptions));
    }

    private async __apiGenerateApiKey(
        request: XcelsiorApi.ApiGenerateApiKeyApiKeysGeneratePostRequest = {},
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { name, scope } = request;
        const _queryParams: Record<string, unknown> = {
            name,
            scope,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/keys/generate",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/keys/generate");
    }

    /**
     * List all API keys for the authenticated user (keys are redacted).
     *
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.auth.apiListKeys()
     */
    public apiListKeys(requestOptions?: AuthClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiListKeys(requestOptions));
    }

    private async __apiListKeys(requestOptions?: AuthClient.RequestOptions): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/keys",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.XcelsiorApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/keys");
    }

    /**
     * Revoke an API key by its preview string.
     *
     * @param {XcelsiorApi.ApiRevokeKeyApiKeysKeyPreviewDeleteRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.auth.apiRevokeKey({
     *         key_preview: "key_preview"
     *     })
     */
    public apiRevokeKey(
        request: XcelsiorApi.ApiRevokeKeyApiKeysKeyPreviewDeleteRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiRevokeKey(request, requestOptions));
    }

    private async __apiRevokeKey(
        request: XcelsiorApi.ApiRevokeKeyApiKeysKeyPreviewDeleteRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { key_preview: keyPreview } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/keys/${core.url.encodePathParam(keyPreview)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "DELETE", "/api/keys/{key_preview}");
    }

    /**
     * Initiate a password reset. Returns a one-time reset token (dev mode).
     *
     * @param {XcelsiorApi.PasswordResetRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.auth.apiAuthPasswordReset({
     *         email: "email"
     *     })
     */
    public apiAuthPasswordReset(
        request: XcelsiorApi.PasswordResetRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiAuthPasswordReset(request, requestOptions));
    }

    private async __apiAuthPasswordReset(
        request: XcelsiorApi.PasswordResetRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/auth/password-reset",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/auth/password-reset");
    }

    /**
     * Confirm password reset with token and set new password.
     *
     * @param {XcelsiorApi.PasswordResetConfirm} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.auth.apiAuthPasswordResetConfirm({
     *         token: "token",
     *         new_password: "new_password"
     *     })
     */
    public apiAuthPasswordResetConfirm(
        request: XcelsiorApi.PasswordResetConfirm,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiAuthPasswordResetConfirm(request, requestOptions));
    }

    private async __apiAuthPasswordResetConfirm(
        request: XcelsiorApi.PasswordResetConfirm,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/auth/password-reset/confirm",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/auth/password-reset/confirm",
        );
    }

    /**
     * Change password for the authenticated user.
     *
     * @param {XcelsiorApi.ChangePasswordRequest} request
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.auth.apiAuthChangePassword({
     *         current_password: "current_password",
     *         new_password: "new_password"
     *     })
     */
    public apiAuthChangePassword(
        request: XcelsiorApi.ChangePasswordRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiAuthChangePassword(request, requestOptions));
    }

    private async __apiAuthChangePassword(
        request: XcelsiorApi.ChangePasswordRequest,
        requestOptions?: AuthClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/auth/change-password",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/auth/change-password");
    }

    /**
     * Export all personal data for the current user (PIPEDA right).
     *
     * Returns a JSON bundle of all user data: profile, jobs, billing,
     * reputation, artifacts, and consent records.
     *
     * @param {AuthClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.auth.apiDataExport()
     */
    public apiDataExport(requestOptions?: AuthClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiDataExport(requestOptions));
    }

    private async __apiDataExport(requestOptions?: AuthClient.RequestOptions): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/auth/me/data-export",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.XcelsiorApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/auth/me/data-export");
    }
}
