// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         provider_id: "provider_id"
 *     }
 */
export interface PayoutProvidersRequest {
    provider_id: string;
    job_id?: string;
    total_cad?: number;
}
