// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         provider_id: "provider_id",
 *         email: "email"
 *     }
 */
export interface ProviderRegisterRequest {
    provider_id: string;
    email: string;
    provider_type?: string;
    corporation_name?: string;
    business_number?: string;
    gst_hst_number?: string;
    province?: string;
    legal_name?: string;
}
