"""`requirements.txt` must still agree with the lockfile it was exported from.

`requirements.txt` carries the header "This file was autogenerated by uv" and is
then never checked against the thing that generated it. It went stale on
2026-07-28, one day before `uv.lock` moved, and stayed that way for a week.

The failure is quiet in the worst way. `pip install -r requirements.txt` does not
warn and does not install a slightly-wrong version — it **aborts** on the first
hash mismatch:

    stripe==15.3.1 ... stripe-15.3.1-py3-none-any.whl
        Expected sha256 0a525e4550b5bf7f...
        Expected     or 3c04e8cc9ec8d954...
             Got        f7c87a9a9072db73...

One entry of 98 was wrong, and it took the whole file with it. Worse, on the
Stripe SDK, on a host holding live Stripe credentials, a hash mismatch is what a
supply-chain compromise looks like. It was not one — PyPI's published digest is
exactly what pip downloaded, and `uv.lock` records that digest correctly — but
somebody had to spend the time proving that.

**Who this breaks.** Production images are safe: the `Dockerfile` runs
`uv sync --frozen`. The casualties are `setup.sh`, which pip-installs this file
to build a contributor's environment, and `.github/workflows/live-gates.yml`,
which does the same in CI. Both were broken and neither said so, because neither
had run.

The check is a pure parse of two files in the repository — no network, no
install — so it costs nothing and cannot flake. `uv.lock` is the source of
truth; this asserts the export still reflects it.
"""

from __future__ import annotations

import pathlib
import re
import tomllib

ROOT = pathlib.Path(__file__).resolve().parent.parent
REQUIREMENTS = ROOT / "requirements.txt"
LOCKFILE = ROOT / "uv.lock"

_ENTRY = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s\\]+)")
_HASH = re.compile(r"--hash=sha256:([0-9a-f]{64})")


def _normalise(name: str) -> str:
    return name.lower().replace("_", "-")


def _exported() -> dict[tuple[str, str], set[str]]:
    """Every pinned package in the export, with the hashes pip will accept."""
    pinned: dict[tuple[str, str], set[str]] = {}
    key: tuple[str, str] | None = None
    for line in REQUIREMENTS.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        match = _ENTRY.match(stripped)
        if match:
            key = (_normalise(match.group(1)), match.group(2))
            pinned.setdefault(key, set())
        if key:
            pinned[key].update(_HASH.findall(stripped))
    return pinned


def _locked() -> dict[tuple[str, str], set[str]]:
    """Every package in `uv.lock`, with the digests it records."""
    data = tomllib.loads(LOCKFILE.read_text(encoding="utf-8"))
    locked: dict[tuple[str, str], set[str]] = {}
    for package in data.get("package", []):
        name = _normalise(str(package.get("name", "")))
        version = str(package.get("version", ""))
        if not name or not version:
            continue
        digests: set[str] = set()
        sdist = package.get("sdist")
        if isinstance(sdist, dict):
            digests.add(str(sdist.get("hash", "")).removeprefix("sha256:"))
        for wheel in package.get("wheels", []) or []:
            if isinstance(wheel, dict):
                digests.add(str(wheel.get("hash", "")).removeprefix("sha256:"))
        locked[(name, version)] = {d for d in digests if d}
    return locked


def test_the_two_files_are_both_parseable():
    """Prove the reach.

    Both parsers key off file formats that could change under them. If either
    returned nothing, every assertion below would pass while comparing empty
    sets — a guard that reports clean because it is looking at nothing.
    """
    exported, locked = _exported(), _locked()
    assert len(exported) > 50, f"parsed only {len(exported)} entries from requirements.txt"
    assert len(locked) > 50, f"parsed only {len(locked)} packages from uv.lock"


def test_every_exported_pin_exists_in_the_lockfile():
    """A package or version in the export that the lock does not have."""
    exported, locked = _exported(), _locked()
    missing = sorted(f"{n}=={v}" for (n, v) in exported if (n, v) not in locked)
    assert not missing, (
        "requirements.txt pins packages or versions absent from uv.lock, so it "
        f"was exported from an older lock: {missing[:10]}. "
        "Regenerate with scripts/export-requirements.sh."
    )


def test_every_exported_hash_is_one_the_lockfile_records():
    """The check that would have caught the stripe drift.

    pip aborts the entire install on the first mismatch, so a single stale entry
    disables the file. Both of `stripe==15.3.1`'s exported hashes matched
    neither artifact PyPI publishes.
    """
    exported, locked = _exported(), _locked()
    drifted = []
    for (name, version), hashes in sorted(exported.items()):
        recorded = locked.get((name, version))
        if recorded is None or not hashes:
            continue
        if not (hashes & recorded):
            drifted.append(f"{name}=={version}")
    assert not drifted, (
        "requirements.txt pins hashes that uv.lock does not record for those "
        f"versions: {drifted[:10]}. `pip install -r requirements.txt` aborts on "
        "the first of these, which breaks setup.sh and live-gates.yml. "
        "Regenerate with scripts/export-requirements.sh."
    )
