// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface SovereignQueueRequest {
    canada_only?: boolean;
    province?: string;
    trust_tier?: string;
}
