// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name",
 *         vram_needed_gb: 1.1,
 *         max_bid: 1.1
 *     }
 */
export interface SpotJobIn {
    name: string;
    vram_needed_gb: number;
    max_bid: number;
    priority?: number;
    tier?: string | null;
    image?: string | null;
}
