// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         notification_id: "notification_id"
 *     }
 */
export interface DeleteNotificationsRequest {
    notification_id: string;
}
