// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         name: "name"
 *     }
 */
export interface JobIn {
    name: string;
    vram_needed_gb?: number;
    priority?: number;
    tier?: string | null;
    num_gpus?: number;
    host_id?: string | null;
    gpu_model?: string | null;
    nfs_server?: string | null;
    nfs_path?: string | null;
    nfs_mount_point?: string | null;
    image?: string | null;
    interactive?: boolean;
    command?: string | null;
    ssh_port?: number;
    max_bid?: number | null;
}
