// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         volume_id: "volume_id",
 *         instance_id: "instance_id"
 *     }
 */
export interface VolumeAttachRequest {
    volume_id: string;
    instance_id: string;
    mount_path?: string;
    mode?: VolumeAttachRequest.Mode;
}

export namespace VolumeAttachRequest {
    export const Mode = {
        Rw: "rw",
        Ro: "ro",
    } as const;
    export type Mode = (typeof Mode)[keyof typeof Mode];
}
