// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as XcelsiorApi from "../../../index.js";

export declare namespace JobsClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Job submission, scheduling, and lifecycle management.
 */
export class JobsClient {
    protected readonly _options: NormalizedClientOptions<JobsClient.Options>;

    constructor(options: JobsClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Submit a job to the queue. Tier overrides priority.
     *
     * Multi-GPU: Set num_gpus > 1 for multi-GPU jobs.
     * NFS: Optionally specify nfs_server + nfs_path for shared storage.
     *
     * @param {XcelsiorApi.JobIn} request
     * @param {JobsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.jobs.apiSubmitJob({
     *         name: "name",
     *         vram_needed_gb: 1.1
     *     })
     */
    public apiSubmitJob(
        request: XcelsiorApi.JobIn,
        requestOptions?: JobsClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiSubmitJob(request, requestOptions));
    }

    private async __apiSubmitJob(
        request: XcelsiorApi.JobIn,
        requestOptions?: JobsClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "job",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/job");
    }

    /**
     * List jobs. Optional filter by status.
     *
     * @param {XcelsiorApi.ApiListJobsJobsGetRequest} request
     * @param {JobsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.jobs.apiListJobs()
     */
    public apiListJobs(
        request: XcelsiorApi.ApiListJobsJobsGetRequest = {},
        requestOptions?: JobsClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiListJobs(request, requestOptions));
    }

    private async __apiListJobs(
        request: XcelsiorApi.ApiListJobsJobsGetRequest = {},
        requestOptions?: JobsClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { status } = request;
        const _queryParams: Record<string, unknown> = {
            status,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "jobs",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/jobs");
    }

    /**
     * Get a specific job by ID.
     *
     * @param {XcelsiorApi.ApiGetJobJobJobIdGetRequest} request
     * @param {JobsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.jobs.apiGetJob({
     *         job_id: "job_id"
     *     })
     */
    public apiGetJob(
        request: XcelsiorApi.ApiGetJobJobJobIdGetRequest,
        requestOptions?: JobsClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiGetJob(request, requestOptions));
    }

    private async __apiGetJob(
        request: XcelsiorApi.ApiGetJobJobJobIdGetRequest,
        requestOptions?: JobsClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { job_id: jobId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `job/${core.url.encodePathParam(jobId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/job/{job_id}");
    }

    /**
     * Update a job's status.
     *
     * @param {XcelsiorApi.StatusUpdate} request
     * @param {JobsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.jobs.apiUpdateJob({
     *         job_id: "job_id",
     *         status: "status"
     *     })
     */
    public apiUpdateJob(
        request: XcelsiorApi.StatusUpdate,
        requestOptions?: JobsClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiUpdateJob(request, requestOptions));
    }

    private async __apiUpdateJob(
        request: XcelsiorApi.StatusUpdate,
        requestOptions?: JobsClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { job_id: jobId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `job/${core.url.encodePathParam(jobId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "PATCH", "/job/{job_id}");
    }

    /**
     * Process the job queue — assign jobs to hosts.
     *
     * @param {JobsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.jobs.apiProcessQueue()
     */
    public apiProcessQueue(requestOptions?: JobsClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiProcessQueue(requestOptions));
    }

    private async __apiProcessQueue(
        requestOptions?: JobsClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "queue/process",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.XcelsiorApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/queue/process");
    }

    /**
     * Run a full failover cycle: check hosts, requeue orphaned jobs, reassign.
     *
     * @param {JobsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.jobs.apiFailover()
     */
    public apiFailover(requestOptions?: JobsClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiFailover(requestOptions));
    }

    private async __apiFailover(requestOptions?: JobsClient.RequestOptions): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "failover",
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.XcelsiorApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/failover");
    }

    /**
     * Manually requeue a failed or stuck job.
     *
     * @param {XcelsiorApi.ApiRequeueJobJobJobIdRequeuePostRequest} request
     * @param {JobsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.jobs.apiRequeueJob({
     *         job_id: "job_id"
     *     })
     */
    public apiRequeueJob(
        request: XcelsiorApi.ApiRequeueJobJobJobIdRequeuePostRequest,
        requestOptions?: JobsClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiRequeueJob(request, requestOptions));
    }

    private async __apiRequeueJob(
        request: XcelsiorApi.ApiRequeueJobJobJobIdRequeuePostRequest,
        requestOptions?: JobsClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { job_id: jobId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `job/${core.url.encodePathParam(jobId)}/requeue`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/job/{job_id}/requeue");
    }

    /**
     * Stream real-time logs for a specific job via Server-Sent Events.
     *
     * Connect with `EventSource('/jobs/{job_id}/logs/stream')` in the browser
     * or `curl -N` from the CLI. Replays buffered log lines on connect, then
     * live-tails new log entries until the client disconnects or the job completes.
     *
     * Events emitted:
     * - `job_log` — individual log line (data: {job_id, timestamp, line, level})
     * - `job_status` — status change (data: {job_id, status})
     * - `connected` — initial handshake (data: {job_id, status: "streaming"})
     *
     * @param {XcelsiorApi.ApiJobLogStreamJobsJobIdLogsStreamGetRequest} request
     * @param {JobsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.jobs.apiJobLogStream({
     *         job_id: "job_id"
     *     })
     */
    public apiJobLogStream(
        request: XcelsiorApi.ApiJobLogStreamJobsJobIdLogsStreamGetRequest,
        requestOptions?: JobsClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiJobLogStream(request, requestOptions));
    }

    private async __apiJobLogStream(
        request: XcelsiorApi.ApiJobLogStreamJobsJobIdLogsStreamGetRequest,
        requestOptions?: JobsClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { job_id: jobId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `jobs/${core.url.encodePathParam(jobId)}/logs/stream`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/jobs/{job_id}/logs/stream");
    }

    /**
     * Get buffered log lines for a job (non-streaming).
     *
     * Returns the last `limit` log lines from the in-memory buffer.
     * For real-time streaming, use `/jobs/{job_id}/logs/stream` (SSE).
     *
     * @param {XcelsiorApi.ApiJobLogsJobsJobIdLogsGetRequest} request
     * @param {JobsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.jobs.apiJobLogs({
     *         job_id: "job_id"
     *     })
     */
    public apiJobLogs(
        request: XcelsiorApi.ApiJobLogsJobsJobIdLogsGetRequest,
        requestOptions?: JobsClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiJobLogs(request, requestOptions));
    }

    private async __apiJobLogs(
        request: XcelsiorApi.ApiJobLogsJobsJobIdLogsGetRequest,
        requestOptions?: JobsClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { job_id: jobId, limit } = request;
        const _queryParams: Record<string, unknown> = {
            limit,
        };
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `jobs/${core.url.encodePathParam(jobId)}/logs`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/jobs/{job_id}/logs");
    }

    /**
     * List all priority tiers with their multipliers.
     *
     * @param {JobsClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.jobs.apiListTiers()
     */
    public apiListTiers(requestOptions?: JobsClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__apiListTiers(requestOptions));
    }

    private async __apiListTiers(requestOptions?: JobsClient.RequestOptions): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "tiers",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.XcelsiorApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/tiers");
    }
}
