// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         challenge_id: "challenge_id"
 *     }
 */
export interface PasskeyAuthenticateOptionsRequest {
    challenge_id: string;
}
