// This file was auto-generated by Fern from our API Definition.

export interface AlertConfig {
    email_enabled?: (boolean | null) | undefined;
    smtp_host?: (string | null) | undefined;
    smtp_port?: (number | null) | undefined;
    smtp_user?: (string | null) | undefined;
    smtp_pass?: (string | null) | undefined;
    email_from?: (string | null) | undefined;
    email_to?: (string | null) | undefined;
    telegram_enabled?: (boolean | null) | undefined;
    telegram_bot_token?: (string | null) | undefined;
    telegram_chat_id?: (string | null) | undefined;
}
