// This file was auto-generated by Fern from our API Definition.

export interface BuildIn {
    model: string;
    base_image?: string | undefined;
    quantize?: (string | null) | undefined;
    push?: boolean | undefined;
}
