// This file was auto-generated by Fern from our API Definition.

export interface LegalRequestRecord {
    request_type?: string | undefined;
    jurisdiction?: string | undefined;
    authority?: string | undefined;
    scope?: string | undefined;
    notes?: string | undefined;
}
