// This file was auto-generated by Fern from our API Definition.

export interface PiaCheckRequest {
    data_origin_province?: string | undefined;
    processing_province?: string | undefined;
    data_contains_pi?: boolean | undefined;
}
