// This file was auto-generated by Fern from our API Definition.

export interface ServerlessEndpointCreate {
    name?: string | undefined;
    mode?: string | undefined;
    model_name?: string | undefined;
    model_ref?: string | undefined;
    image_ref?: string | undefined;
    docker_image?: string | undefined;
    gpu_type?: string | undefined;
    gpu_tier?: string | undefined;
    gpu_count?: number | undefined;
    region?: string | undefined;
    min_workers?: number | undefined;
    max_workers?: number | undefined;
    max_concurrency?: number | undefined;
    idle_timeout_sec?: number | undefined;
    scaledown_window_sec?: (number | null) | undefined;
    scaling_policy_type?: string | undefined;
    scaling_policy_value?: number | undefined;
    startup_command?: string | undefined;
    http_port?: number | undefined;
    health_check_path?: string | undefined;
    health_endpoint?: string | undefined;
    cuda_version?: string | undefined;
    request_timeout_sec?: number | undefined;
    max_request_bytes?: number | undefined;
    env?: Record<string, string> | undefined;
}
