// This file was auto-generated by Fern from our API Definition.

export interface SovereignQueueRequest {
    canada_only?: boolean | undefined;
    province?: string | undefined;
    trust_tier?: string | undefined;
}
