// This file was auto-generated by Fern from our API Definition.

export interface TelemetryPayload {
    host_id: string;
    timestamp?: number | undefined;
    metrics?: Record<string, unknown> | undefined;
}
