// This file was auto-generated by Fern from our API Definition.

/**
 * OpenAI-compatible inference request for /v1/inference.
 */
export interface V1InferenceRequest {
    /** Model name or HuggingFace repo */
    model: string;
    /** Text input(s) for inference */
    inputs: V1InferenceRequest.Inputs;
    max_tokens?: number | undefined;
    temperature?: number | undefined;
    /** Stream response via SSE */
    stream?: boolean | undefined;
}

export namespace V1InferenceRequest {
    /**
     * Text input(s) for inference
     */
    export type Inputs = string[] | string;
}
