// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as XcelsiorApi from "../../../index.js";

export declare namespace InferenceV2Client {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class InferenceV2Client {
    protected readonly _options: NormalizedClientOptions<InferenceV2Client.Options>;

    constructor(options: InferenceV2Client.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Synchronous inference endpoint (OpenAI-compatible path).
     *
     * Submits an inference request and polls for results up to 30 seconds.
     * If stream=true, returns SSE text/event-stream with token deltas.
     *
     * @param {XcelsiorApi.V1InferenceRequest} request
     * @param {InferenceV2Client.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.inferenceV2.sync({
     *         model: "model",
     *         inputs: ["inputs"]
     *     })
     */
    public sync(
        request: XcelsiorApi.V1InferenceRequest,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__sync(request, requestOptions));
    }

    private async __sync(
        request: XcelsiorApi.V1InferenceRequest,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "v1/inference",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/inference");
    }

    /**
     * Asynchronous inference — returns job_id immediately for polling.
     *
     * @param {XcelsiorApi.V1InferenceRequest} request
     * @param {InferenceV2Client.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.inferenceV2.async({
     *         model: "model",
     *         inputs: ["inputs"]
     *     })
     */
    public async(
        request: XcelsiorApi.V1InferenceRequest,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__async(request, requestOptions));
    }

    private async __async(
        request: XcelsiorApi.V1InferenceRequest,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "v1/inference/async",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/inference/async");
    }

    /**
     * Poll for inference results by job_id.
     *
     * @param {XcelsiorApi.PollInferenceV2Request} request
     * @param {InferenceV2Client.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.inferenceV2.poll({
     *         job_id: "job_id"
     *     })
     */
    public poll(
        request: XcelsiorApi.PollInferenceV2Request,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__poll(request, requestOptions));
    }

    private async __poll(
        request: XcelsiorApi.PollInferenceV2Request,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { job_id: jobId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `v1/inference/${core.url.encodePathParam(jobId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/v1/inference/{job_id}");
    }

    /**
     * List inference endpoints for the current user.
     *
     * @param {InferenceV2Client.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.inferenceV2.listEndpoints()
     */
    public listEndpoints(requestOptions?: InferenceV2Client.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__listEndpoints(requestOptions));
    }

    private async __listEndpoints(
        requestOptions?: InferenceV2Client.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/v2/inference/endpoints",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.XcelsiorApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v2/inference/endpoints");
    }

    /**
     * Create a serverless inference endpoint.
     *
     * If min_workers >= 1, a worker container is provisioned immediately.
     * Billing is real-time from credits (per-second compute + per-token inference).
     *
     * @param {XcelsiorApi.InferenceEndpointCreate} request
     * @param {InferenceV2Client.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.inferenceV2.createEndpoint({
     *         model_name: "model_name"
     *     })
     */
    public createEndpoint(
        request: XcelsiorApi.InferenceEndpointCreate,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__createEndpoint(request, requestOptions));
    }

    private async __createEndpoint(
        request: XcelsiorApi.InferenceEndpointCreate,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/v2/inference/endpoints",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/v2/inference/endpoints");
    }

    /**
     * Get inference endpoint details.
     *
     * @param {XcelsiorApi.GetEndpointInferenceV2Request} request
     * @param {InferenceV2Client.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.inferenceV2.getEndpoint({
     *         endpoint_id: "endpoint_id"
     *     })
     */
    public getEndpoint(
        request: XcelsiorApi.GetEndpointInferenceV2Request,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__getEndpoint(request, requestOptions));
    }

    private async __getEndpoint(
        request: XcelsiorApi.GetEndpointInferenceV2Request,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/v2/inference/endpoints/${core.url.encodePathParam(endpointId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v2/inference/endpoints/{endpoint_id}",
        );
    }

    /**
     * Delete an inference endpoint.
     *
     * @param {XcelsiorApi.DeleteEndpointInferenceV2Request} request
     * @param {InferenceV2Client.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.inferenceV2.deleteEndpoint({
     *         endpoint_id: "endpoint_id"
     *     })
     */
    public deleteEndpoint(
        request: XcelsiorApi.DeleteEndpointInferenceV2Request,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__deleteEndpoint(request, requestOptions));
    }

    private async __deleteEndpoint(
        request: XcelsiorApi.DeleteEndpointInferenceV2Request,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/v2/inference/endpoints/${core.url.encodePathParam(endpointId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v2/inference/endpoints/{endpoint_id}",
        );
    }

    /**
     * Get health status for an inference endpoint and its workers.
     *
     * @param {XcelsiorApi.GetEndpointHealthInferenceV2Request} request
     * @param {InferenceV2Client.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.inferenceV2.getEndpointHealth({
     *         endpoint_id: "endpoint_id"
     *     })
     */
    public getEndpointHealth(
        request: XcelsiorApi.GetEndpointHealthInferenceV2Request,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__getEndpointHealth(request, requestOptions));
    }

    private async __getEndpointHealth(
        request: XcelsiorApi.GetEndpointHealthInferenceV2Request,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/v2/inference/endpoints/${core.url.encodePathParam(endpointId)}/health`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v2/inference/endpoints/{endpoint_id}/health",
        );
    }

    /**
     * Get usage stats for an inference endpoint.
     *
     * @param {XcelsiorApi.GetEndpointUsageInferenceV2Request} request
     * @param {InferenceV2Client.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.inferenceV2.getEndpointUsage({
     *         endpoint_id: "endpoint_id"
     *     })
     */
    public getEndpointUsage(
        request: XcelsiorApi.GetEndpointUsageInferenceV2Request,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__getEndpointUsage(request, requestOptions));
    }

    private async __getEndpointUsage(
        request: XcelsiorApi.GetEndpointUsageInferenceV2Request,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/v2/inference/endpoints/${core.url.encodePathParam(endpointId)}/usage`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v2/inference/endpoints/{endpoint_id}/usage",
        );
    }

    /**
     * OpenAI-compatible chat completions endpoint.
     *
     * Routes to a serverless inference endpoint running the requested model.
     *
     * @param {XcelsiorApi.ChatCompletionRequest} request
     * @param {InferenceV2Client.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.inferenceV2.chatCompletions({
     *         model: "model"
     *     })
     */
    public chatCompletions(
        request: XcelsiorApi.ChatCompletionRequest,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__chatCompletions(request, requestOptions));
    }

    private async __chatCompletions(
        request: XcelsiorApi.ChatCompletionRequest,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "v1/chat/completions",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/v1/chat/completions");
    }

    /**
     * Worker callback: mark inference request as completed with results.
     *
     * @param {XcelsiorApi.CompleteInferenceV2Request} request
     * @param {InferenceV2Client.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.inferenceV2.complete({
     *         request_id: "request_id"
     *     })
     */
    public complete(
        request: XcelsiorApi.CompleteInferenceV2Request,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__complete(request, requestOptions));
    }

    private async __complete(
        request: XcelsiorApi.CompleteInferenceV2Request,
        requestOptions?: InferenceV2Client.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { request_id: requestId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/v2/inference/complete/${core.url.encodePathParam(requestId)}`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v2/inference/complete/{request_id}",
        );
    }
}
