// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         host_id: "host_id",
 *         gpu_model: "gpu_model",
 *         vram_gb: 1.1,
 *         price_per_hour: 1.1
 *     }
 */
export interface RigListing {
    host_id: string;
    gpu_model: string;
    vram_gb: number;
    price_per_hour: number;
    description?: string;
    owner?: string;
}
