// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface SearchMarketplaceRequest {
    gpu_model?: string | null;
    min_vram?: number | null;
    max_price?: number | null;
    province?: string | null;
    country?: string | null;
    min_reputation?: number | null;
    sort_by?: string;
    limit?: number;
}
