// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         purpose: "purpose"
 *     }
 */
export interface WithdrawConsentV2PrivacyRequest {
    purpose: string;
}
