// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface AutoTopupConfig {
    enabled?: boolean;
    amount_cad?: number;
    threshold_cad?: number;
    stripe_payment_method_id?: string;
}
