// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         deposit_id: "deposit_id"
 *     }
 */
export interface CryptoDepositStatusBillingRequest {
    deposit_id: string;
}
