// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface EstimateRequest {
    gpu_model?: string;
    duration_hours?: number;
    spot?: boolean;
    sovereignty?: boolean;
    is_canadian?: boolean;
}
