// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         customer_id: "customer_id"
 *     }
 */
export interface ExportCafBillingRequest {
    customer_id: string;
    period_start?: number;
    period_end?: number;
    format?: string;
}
