// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         job_id: "job_id",
 *         exit_code: 1
 *     }
 */
export interface RefundRequest {
    job_id: string;
    exit_code: number;
    failure_reason?: string;
}
