// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         endpoint_id: "endpoint_id"
 *     }
 */
export interface GetEndpointInferenceV2Request {
    endpoint_id: string;
}
