// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         model_name: "model_name"
 *     }
 */
export interface InferenceEndpointCreate {
    model_name: string;
    gpu_type?: string;
    region?: string;
    docker_image?: string;
    min_workers?: number;
    max_workers?: number;
    max_batch_size?: number;
    max_concurrent?: number;
    scaledown_window_sec?: number;
    mode?: string;
    health_endpoint?: string;
    api_format?: string;
}
