// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         job_id: "job_id"
 *     }
 */
export interface ApiListArtifactsApiArtifactsJobIdGetRequest {
    job_id: string;
}
