// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         model: "model",
 *         inputs: ["inputs"]
 *     }
 */
export interface InferenceRequest {
    /** Model name or HuggingFace repo (e.g. 'distilbert-base-uncased-finetuned-sst-2-english') */
    model: string;
    /** Text input(s) for inference */
    inputs: InferenceRequest.Inputs;
    /** Preferred GPU model or 'any' */
    gpu_model?: string;
    max_tokens?: number;
    temperature?: number;
    timeout_sec?: number;
}

export namespace InferenceRequest {
    /**
     * Text input(s) for inference
     */
    export type Inputs = string[] | string;
}
