// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         slurm_job_id: "slurm_job_id"
 *     }
 */
export interface ApiSlurmStatusApiSlurmStatusSlurmJobIdGetRequest {
    slurm_job_id: string;
}
