// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface PiaCheckRequest {
    data_origin_province?: string;
    processing_province?: string;
    data_contains_pi?: boolean;
}
