// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import { handleNonStatusCodeError } from "../../../../errors/handleNonStatusCodeError.js";
import * as errors from "../../../../errors/index.js";
import * as XcelsiorApi from "../../../index.js";

export declare namespace ServerlessClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class ServerlessClient {
    protected readonly _options: NormalizedClientOptions<ServerlessClient.Options>;

    constructor(options: ServerlessClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Feature-flag probe for dashboard rollout (session optional).
     *
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.serverless.enabled()
     */
    public enabled(requestOptions?: ServerlessClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__enabled(requestOptions));
    }

    private async __enabled(requestOptions?: ServerlessClient.RequestOptions): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/v2/serverless/enabled",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.XcelsiorApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v2/serverless/enabled");
    }

    /**
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.serverless.listEndpoints()
     */
    public listEndpoints(requestOptions?: ServerlessClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__listEndpoints(requestOptions));
    }

    private async __listEndpoints(
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/v2/serverless/endpoints",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.XcelsiorApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v2/serverless/endpoints");
    }

    /**
     * @param {XcelsiorApi.ServerlessEndpointCreate} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.createEndpoint({})
     */
    public createEndpoint(
        request: XcelsiorApi.ServerlessEndpointCreate,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__createEndpoint(request, requestOptions));
    }

    private async __createEndpoint(
        request: XcelsiorApi.ServerlessEndpointCreate,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/v2/serverless/endpoints",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/v2/serverless/endpoints");
    }

    /**
     * @param {XcelsiorApi.GetEndpointServerlessRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.getEndpoint({
     *         endpoint_id: "endpoint_id"
     *     })
     */
    public getEndpoint(
        request: XcelsiorApi.GetEndpointServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__getEndpoint(request, requestOptions));
    }

    private async __getEndpoint(
        request: XcelsiorApi.GetEndpointServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/v2/serverless/endpoints/${core.url.encodePathParam(endpointId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v2/serverless/endpoints/{endpoint_id}",
        );
    }

    /**
     * @param {XcelsiorApi.DeleteEndpointServerlessRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.deleteEndpoint({
     *         endpoint_id: "endpoint_id"
     *     })
     */
    public deleteEndpoint(
        request: XcelsiorApi.DeleteEndpointServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__deleteEndpoint(request, requestOptions));
    }

    private async __deleteEndpoint(
        request: XcelsiorApi.DeleteEndpointServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/v2/serverless/endpoints/${core.url.encodePathParam(endpointId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v2/serverless/endpoints/{endpoint_id}",
        );
    }

    /**
     * @param {XcelsiorApi.ServerlessEndpointPatch} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.patchEndpoint({
     *         endpoint_id: "endpoint_id"
     *     })
     */
    public patchEndpoint(
        request: XcelsiorApi.ServerlessEndpointPatch,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__patchEndpoint(request, requestOptions));
    }

    private async __patchEndpoint(
        request: XcelsiorApi.ServerlessEndpointPatch,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/v2/serverless/endpoints/${core.url.encodePathParam(endpointId)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "PATCH",
            "/api/v2/serverless/endpoints/{endpoint_id}",
        );
    }

    /**
     * @param {XcelsiorApi.GetEndpointHealthServerlessRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.getEndpointHealth({
     *         endpoint_id: "endpoint_id"
     *     })
     */
    public getEndpointHealth(
        request: XcelsiorApi.GetEndpointHealthServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__getEndpointHealth(request, requestOptions));
    }

    private async __getEndpointHealth(
        request: XcelsiorApi.GetEndpointHealthServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/v2/serverless/endpoints/${core.url.encodePathParam(endpointId)}/health`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v2/serverless/endpoints/{endpoint_id}/health",
        );
    }

    /**
     * Alias for metrics — dashboard compatibility.
     *
     * @param {XcelsiorApi.GetEndpointUsageServerlessRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.getEndpointUsage({
     *         endpoint_id: "endpoint_id"
     *     })
     */
    public getEndpointUsage(
        request: XcelsiorApi.GetEndpointUsageServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__getEndpointUsage(request, requestOptions));
    }

    private async __getEndpointUsage(
        request: XcelsiorApi.GetEndpointUsageServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/v2/serverless/endpoints/${core.url.encodePathParam(endpointId)}/usage`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v2/serverless/endpoints/{endpoint_id}/usage",
        );
    }

    /**
     * @param {XcelsiorApi.ListKeysServerlessRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.listKeys({
     *         endpoint_id: "endpoint_id"
     *     })
     */
    public listKeys(
        request: XcelsiorApi.ListKeysServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__listKeys(request, requestOptions));
    }

    private async __listKeys(
        request: XcelsiorApi.ListKeysServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/v2/serverless/endpoints/${core.url.encodePathParam(endpointId)}/keys`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v2/serverless/endpoints/{endpoint_id}/keys",
        );
    }

    /**
     * @param {XcelsiorApi.ApiKeyCreateRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.createKey({
     *         endpoint_id: "endpoint_id"
     *     })
     */
    public createKey(
        request: XcelsiorApi.ApiKeyCreateRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__createKey(request, requestOptions));
    }

    private async __createKey(
        request: XcelsiorApi.ApiKeyCreateRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/v2/serverless/endpoints/${core.url.encodePathParam(endpointId)}/keys`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/api/v2/serverless/endpoints/{endpoint_id}/keys",
        );
    }

    /**
     * @param {XcelsiorApi.RevokeKeyServerlessRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.revokeKey({
     *         endpoint_id: "endpoint_id",
     *         key_id: "key_id"
     *     })
     */
    public revokeKey(
        request: XcelsiorApi.RevokeKeyServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__revokeKey(request, requestOptions));
    }

    private async __revokeKey(
        request: XcelsiorApi.RevokeKeyServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId, key_id: keyId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/v2/serverless/endpoints/${core.url.encodePathParam(endpointId)}/keys/${core.url.encodePathParam(keyId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v2/serverless/endpoints/{endpoint_id}/keys/{key_id}",
        );
    }

    /**
     * @param {XcelsiorApi.RunJobServerlessRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.runJob({
     *         endpoint_id: "endpoint_id",
     *         body: {}
     *     })
     */
    public runJob(
        request: XcelsiorApi.RunJobServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__runJob(request, requestOptions));
    }

    private async __runJob(
        request: XcelsiorApi.RunJobServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId, body: _body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `v1/serverless/${core.url.encodePathParam(endpointId)}/run`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/serverless/{endpoint_id}/run",
        );
    }

    /**
     * @param {XcelsiorApi.RunJobSyncServerlessRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.runJobSync({
     *         endpoint_id: "endpoint_id",
     *         body: {}
     *     })
     */
    public runJobSync(
        request: XcelsiorApi.RunJobSyncServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__runJobSync(request, requestOptions));
    }

    private async __runJobSync(
        request: XcelsiorApi.RunJobSyncServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId, body: _body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `v1/serverless/${core.url.encodePathParam(endpointId)}/runsync`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/serverless/{endpoint_id}/runsync",
        );
    }

    /**
     * @param {XcelsiorApi.GetJobStatusServerlessRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.getJobStatus({
     *         endpoint_id: "endpoint_id",
     *         job_id: "job_id"
     *     })
     */
    public getJobStatus(
        request: XcelsiorApi.GetJobStatusServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__getJobStatus(request, requestOptions));
    }

    private async __getJobStatus(
        request: XcelsiorApi.GetJobStatusServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId, job_id: jobId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `v1/serverless/${core.url.encodePathParam(endpointId)}/status/${core.url.encodePathParam(jobId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/serverless/{endpoint_id}/status/{job_id}",
        );
    }

    /**
     * @param {XcelsiorApi.StreamJobServerlessRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.streamJob({
     *         endpoint_id: "endpoint_id",
     *         job_id: "job_id"
     *     })
     */
    public streamJob(
        request: XcelsiorApi.StreamJobServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__streamJob(request, requestOptions));
    }

    private async __streamJob(
        request: XcelsiorApi.StreamJobServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId, job_id: jobId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `v1/serverless/${core.url.encodePathParam(endpointId)}/stream/${core.url.encodePathParam(jobId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/serverless/{endpoint_id}/stream/{job_id}",
        );
    }

    /**
     * @param {XcelsiorApi.CancelJobServerlessRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.cancelJob({
     *         endpoint_id: "endpoint_id",
     *         job_id: "job_id"
     *     })
     */
    public cancelJob(
        request: XcelsiorApi.CancelJobServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__cancelJob(request, requestOptions));
    }

    private async __cancelJob(
        request: XcelsiorApi.CancelJobServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId, job_id: jobId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `v1/serverless/${core.url.encodePathParam(endpointId)}/cancel/${core.url.encodePathParam(jobId)}`,
            ),
            method: "POST",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/serverless/{endpoint_id}/cancel/{job_id}",
        );
    }

    /**
     * @param {XcelsiorApi.ChatCompletionRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.chatCompletions({
     *         endpoint_id: "endpoint_id",
     *         model: "model"
     *     })
     */
    public chatCompletions(
        request: XcelsiorApi.ChatCompletionRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__chatCompletions(request, requestOptions));
    }

    private async __chatCompletions(
        request: XcelsiorApi.ChatCompletionRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `v1/serverless/${core.url.encodePathParam(endpointId)}/openai/v1/chat/completions`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "POST",
            "/v1/serverless/{endpoint_id}/openai/v1/chat/completions",
        );
    }

    /**
     * @param {XcelsiorApi.ListModelsServerlessRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.listModels({
     *         endpoint_id: "endpoint_id"
     *     })
     */
    public listModels(
        request: XcelsiorApi.ListModelsServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__listModels(request, requestOptions));
    }

    private async __listModels(
        request: XcelsiorApi.ListModelsServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `v1/serverless/${core.url.encodePathParam(endpointId)}/openai/v1/models`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/v1/serverless/{endpoint_id}/openai/v1/models",
        );
    }

    /**
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.serverless.listEndpointsCompat()
     */
    public listEndpointsCompat(requestOptions?: ServerlessClient.RequestOptions): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__listEndpointsCompat(requestOptions));
    }

    private async __listEndpointsCompat(
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/v2/inference/endpoints",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.XcelsiorApiError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "GET", "/api/v2/inference/endpoints");
    }

    /**
     * @param {XcelsiorApi.ServerlessEndpointCreate} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.createEndpointCompat({})
     */
    public createEndpointCompat(
        request: XcelsiorApi.ServerlessEndpointCreate,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__createEndpointCompat(request, requestOptions));
    }

    private async __createEndpointCompat(
        request: XcelsiorApi.ServerlessEndpointCreate,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                "api/v2/inference/endpoints",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(_response.error, _response.rawResponse, "POST", "/api/v2/inference/endpoints");
    }

    /**
     * @param {XcelsiorApi.GetEndpointCompatServerlessRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.getEndpointCompat({
     *         endpoint_id: "endpoint_id"
     *     })
     */
    public getEndpointCompat(
        request: XcelsiorApi.GetEndpointCompatServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__getEndpointCompat(request, requestOptions));
    }

    private async __getEndpointCompat(
        request: XcelsiorApi.GetEndpointCompatServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/v2/inference/endpoints/${core.url.encodePathParam(endpointId)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v2/inference/endpoints/{endpoint_id}",
        );
    }

    /**
     * @param {XcelsiorApi.DeleteEndpointCompatServerlessRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.deleteEndpointCompat({
     *         endpoint_id: "endpoint_id"
     *     })
     */
    public deleteEndpointCompat(
        request: XcelsiorApi.DeleteEndpointCompatServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__deleteEndpointCompat(request, requestOptions));
    }

    private async __deleteEndpointCompat(
        request: XcelsiorApi.DeleteEndpointCompatServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/v2/inference/endpoints/${core.url.encodePathParam(endpointId)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "DELETE",
            "/api/v2/inference/endpoints/{endpoint_id}",
        );
    }

    /**
     * @param {XcelsiorApi.GetEndpointHealthCompatServerlessRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.getEndpointHealthCompat({
     *         endpoint_id: "endpoint_id"
     *     })
     */
    public getEndpointHealthCompat(
        request: XcelsiorApi.GetEndpointHealthCompatServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__getEndpointHealthCompat(request, requestOptions));
    }

    private async __getEndpointHealthCompat(
        request: XcelsiorApi.GetEndpointHealthCompatServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/v2/inference/endpoints/${core.url.encodePathParam(endpointId)}/health`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v2/inference/endpoints/{endpoint_id}/health",
        );
    }

    /**
     * @param {XcelsiorApi.GetEndpointUsageCompatServerlessRequest} request
     * @param {ServerlessClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link XcelsiorApi.UnprocessableEntityError}
     *
     * @example
     *     await client.serverless.getEndpointUsageCompat({
     *         endpoint_id: "endpoint_id"
     *     })
     */
    public getEndpointUsageCompat(
        request: XcelsiorApi.GetEndpointUsageCompatServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): core.HttpResponsePromise<unknown> {
        return core.HttpResponsePromise.fromPromise(this.__getEndpointUsageCompat(request, requestOptions));
    }

    private async __getEndpointUsageCompat(
        request: XcelsiorApi.GetEndpointUsageCompatServerlessRequest,
        requestOptions?: ServerlessClient.RequestOptions,
    ): Promise<core.WithRawResponse<unknown>> {
        const { endpoint_id: endpointId } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(this._options?.headers, requestOptions?.headers);
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.XcelsiorApiEnvironment.Production,
                `api/v2/inference/endpoints/${core.url.encodePathParam(endpointId)}/usage`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: _response.body, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 422:
                    throw new XcelsiorApi.UnprocessableEntityError(
                        _response.error.body as XcelsiorApi.HttpValidationError,
                        _response.rawResponse,
                    );
                default:
                    throw new errors.XcelsiorApiError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        return handleNonStatusCodeError(
            _response.error,
            _response.rawResponse,
            "GET",
            "/api/v2/inference/endpoints/{endpoint_id}/usage",
        );
    }
}
