// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         host_id: "host_id",
 *         month: "month"
 *     }
 */
export interface SlaEnforceRequest {
    host_id: string;
    month: string;
    tier?: string;
    monthly_spend_cad?: number;
}
