#!/usr/bin/env python3
"""Regenerate a review's commit-message transcript from git, not by hand.

`docs/review/p0-commit-messages.md` exists so a reviewer can read what a branch
*claims* without paging through a diff, and so `docs/review/p0-review.md` — which
was written from the messages rather than the code — cites a source that cannot
drift from the branch.

It drifted anyway. Assembled by hand, it documented 16 commits while the branch
carried 18: the commit that added the file, and a later one. A transcript that
silently omits commits is worse than no transcript, because a reviewer takes its
absence as evidence the work is not there.

So: one command, not a hand assembly.

    python3 scripts/generate_review_commit_messages.py
    python3 scripts/generate_review_commit_messages.py --base origin/main --out docs/review/p0-commit-messages.md

**Deliberately not gated** by `tests/test_generated_artifacts_are_current.py`,
unlike `docs/generated/endpoint-inventory.md`. That inventory is derived from the
routes, so it changes only when the surface does, and a gate on it is cheap. This
file is derived from a *commit range* — it changes on every commit to the branch
and again whenever `main` moves. A gate would fail on every commit until someone
regenerated, which trains people to regard the gate as noise. The header below
records the range and count instead, so staleness is visible in the file itself
rather than enforced against it.
"""

from __future__ import annotations

import argparse
import pathlib
import subprocess
import sys

RULE = "=" * 80

#: The residency guard scans prose for placement vocabulary. This file is a
#: transcript of commit messages, several of which are *about* removing that
#: vocabulary — including one describing a text-scanning guard flagging the
#: documentation of the defect it hunts. Without the marker the guard flags this
#: file for quoting it, which is the fifth instance of that recursion in this
#: suite. The marker is the documented, greppable exemption for exactly this:
#: prose whose whole subject is the removal.
MARKER = "residency-guard: documents-removal"


def git(*args: str) -> str:
    return subprocess.run(
        ["git", *args], capture_output=True, text=True, check=True
    ).stdout.rstrip("\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", default="origin/main", help="range start (exclusive)")
    parser.add_argument("--head", default="HEAD", help="range end (inclusive)")
    parser.add_argument("--out", default="docs/review/p0-commit-messages.md")
    args = parser.parse_args()

    rng = f"{args.base}..{args.head}"
    hashes = git("rev-list", "--reverse", rng).split()
    if not hashes:
        print(f"no commits in {rng} — nothing to write", file=sys.stderr)
        return 2

    head_sha = git("rev-parse", "--short", args.head)
    blocks = [
        f"<!-- {MARKER} -->",
        "<!-- Generated by scripts/generate_review_commit_messages.py — do not edit. -->",
        f"<!-- Range {rng} · {len(hashes)} commits · head {head_sha} -->",
        "",
    ]
    for sha in hashes:
        short = git("rev-parse", "--short", sha)
        subject = git("log", "-1", "--format=%s", sha)
        body = git("log", "-1", "--format=%b", sha).strip()
        blocks += [RULE, f"COMMIT {short} — {subject}", RULE, "", body, ""]

    out = pathlib.Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(blocks).rstrip("\n") + "\n")
    print(f"wrote {out} — {len(hashes)} commits from {rng} (head {head_sha})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
