#!/usr/bin/env bash
# Mirror XCELSIOR_AGENT_GATEWAY_SECRET from the API environment into the nginx
# snippet the agent gateway includes.
#
# The two sides must hold the same value: nginx sets X-Xcelsior-Gateway-Auth
# to it on every proxied worker request, and the API compares it with
# hmac.compare_digest. Copying it by hand is how they drift, and drift shows up
# as every agent getting 401 "Agent gateway authentication failed" — so this
# reads the single source of truth instead.
#
# Usage: sudo ./scripts/write-agent-gateway-secret.sh [--check]
#   --check  compare only; exit non-zero if the snippet is missing or stale

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="${PROJECT_DIR}/.env"
TARGET="${XCELSIOR_NGINX_SNIPPET:-/etc/nginx/snippets/agent-gateway-secret.conf}"
CHECK_ONLY=0
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=1

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing ${ENV_FILE}." >&2
  exit 1
fi

# Read the one variable without sourcing the whole file: .env holds live
# credentials, and sourcing it into this shell would export all of them.
SECRET="$(grep -E '^XCELSIOR_AGENT_GATEWAY_SECRET=' "$ENV_FILE" | head -1 | cut -d= -f2- | tr -d '"'"'"'')"

if [[ -z "$SECRET" ]]; then
  echo "XCELSIOR_AGENT_GATEWAY_SECRET is empty in ${ENV_FILE}." >&2
  echo "With XCELSIOR_TRUSTED_AGENT_GATEWAY=1 the API will refuse to start." >&2
  exit 1
fi

RENDERED="# Generated by scripts/write-agent-gateway-secret.sh — do not edit.
# Mirrors XCELSIOR_AGENT_GATEWAY_SECRET from the API environment.
set \$xcelsior_agent_gateway_secret \"${SECRET}\";"

if [[ "$CHECK_ONLY" == "1" ]]; then
  if [[ ! -f "$TARGET" ]]; then
    echo "MISSING: ${TARGET}" >&2
    exit 2
  fi
  if [[ "$(cat "$TARGET")" == "$RENDERED" ]]; then
    echo "OK: ${TARGET} matches the API secret."
    exit 0
  fi
  echo "STALE: ${TARGET} does not match XCELSIOR_AGENT_GATEWAY_SECRET." >&2
  exit 3
fi

mkdir -p "$(dirname "$TARGET")"
umask 027
printf '%s\n' "$RENDERED" > "$TARGET"
chmod 0640 "$TARGET"
# www-data must read it; nobody else should.
chown root:www-data "$TARGET" 2>/dev/null || echo "note: could not chown ${TARGET} (not root?)" >&2

echo "Wrote ${TARGET} (0640 root:www-data)."
echo "Now: nginx -t && systemctl reload nginx"
