// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         gpu_model: "gpu_model"
 *     }
 */
export interface GetSpotHistoryMarketplaceV2Request {
    gpu_model: string;
    hours?: number;
}
