// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface MarketplaceSearchParams {
    gpu_model?: string;
    min_vram_gb?: number;
    max_price_cents?: number;
    region?: string;
    canada_only?: boolean;
    sort_by?: string;
    limit?: number;
}
