// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         allocation_id: "allocation_id"
 *     }
 */
export interface ReleaseMarketplaceV2Request {
    allocation_id: string;
}
