// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         endpoint_id: "endpoint_id"
 *     }
 */
export interface ApiKeyCreateRequest {
    endpoint_id: string;
    name?: string;
    scopes?: string;
    rate_limit_rpm?: number;
}
