// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         endpoint_id: "endpoint_id",
 *         model: "model"
 *     }
 */
export interface ChatCompletionRequest {
    endpoint_id: string;
    model: string;
    messages?: Record<string, unknown>[];
    max_tokens?: number;
    temperature?: number;
    stream?: boolean;
}
