// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         endpoint_id: "endpoint_id",
 *         job_id: "job_id"
 *     }
 */
export interface StreamJobServerlessRequest {
    endpoint_id: string;
    job_id: string;
}
