// This file was auto-generated by Fern from our API Definition.

import { AiAssistantClient } from "./api/resources/aiAssistant/client/Client.js";
import { ArtifactsClient } from "./api/resources/artifacts/client/Client.js";
import { AuthClient } from "./api/resources/auth/client/Client.js";
import { BillingClient } from "./api/resources/billing/client/Client.js";
import { ChatClient } from "./api/resources/chat/client/Client.js";
import { ComplianceClient } from "./api/resources/compliance/client/Client.js";
import { EventsClient } from "./api/resources/events/client/Client.js";
import { GpuClient } from "./api/resources/gpu/client/Client.js";
import { HostsClient } from "./api/resources/hosts/client/Client.js";
import { InferenceClient } from "./api/resources/inference/client/Client.js";
import { InferenceV2Client } from "./api/resources/inferenceV2/client/Client.js";
import { InfrastructureClient } from "./api/resources/infrastructure/client/Client.js";
import { InstancesClient } from "./api/resources/instances/client/Client.js";
import { JurisdictionClient } from "./api/resources/jurisdiction/client/Client.js";
import { MarketplaceClient } from "./api/resources/marketplace/client/Client.js";
import { MarketplaceV2Client } from "./api/resources/marketplaceV2/client/Client.js";
import { MfaClient } from "./api/resources/mfa/client/Client.js";
import { NotificationsClient } from "./api/resources/notifications/client/Client.js";
import { PrivacyClient } from "./api/resources/privacy/client/Client.js";
import { ProvidersClient } from "./api/resources/providers/client/Client.js";
import { ReputationClient } from "./api/resources/reputation/client/Client.js";
import { SlaClient } from "./api/resources/sla/client/Client.js";
import { SpotPricingClient } from "./api/resources/spotPricing/client/Client.js";
import { SshKeysClient } from "./api/resources/sshKeys/client/Client.js";
import { TeamsClient } from "./api/resources/teams/client/Client.js";
import { VerificationClient } from "./api/resources/verification/client/Client.js";
import { VolumesClient } from "./api/resources/volumes/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptions, normalizeClientOptions } from "./BaseClient.js";
import * as core from "./core/index.js";

export declare namespace XcelsiorApiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class XcelsiorApiClient {
    protected readonly _options: NormalizedClientOptions<XcelsiorApiClient.Options>;
    protected _artifacts: ArtifactsClient | undefined;
    protected _auth: AuthClient | undefined;
    protected _billing: BillingClient | undefined;
    protected _chat: ChatClient | undefined;
    protected _aiAssistant: AiAssistantClient | undefined;
    protected _compliance: ComplianceClient | undefined;
    protected _events: EventsClient | undefined;
    protected _gpu: GpuClient | undefined;
    protected _infrastructure: InfrastructureClient | undefined;
    protected _hosts: HostsClient | undefined;
    protected _inference: InferenceClient | undefined;
    protected _inferenceV2: InferenceV2Client | undefined;
    protected _instances: InstancesClient | undefined;
    protected _jurisdiction: JurisdictionClient | undefined;
    protected _marketplace: MarketplaceClient | undefined;
    protected _marketplaceV2: MarketplaceV2Client | undefined;
    protected _mfa: MfaClient | undefined;
    protected _notifications: NotificationsClient | undefined;
    protected _privacy: PrivacyClient | undefined;
    protected _providers: ProvidersClient | undefined;
    protected _reputation: ReputationClient | undefined;
    protected _sla: SlaClient | undefined;
    protected _spotPricing: SpotPricingClient | undefined;
    protected _sshKeys: SshKeysClient | undefined;
    protected _teams: TeamsClient | undefined;
    protected _verification: VerificationClient | undefined;
    protected _volumes: VolumesClient | undefined;

    constructor(options: XcelsiorApiClient.Options = {}) {
        this._options = normalizeClientOptions(options);
    }

    public get artifacts(): ArtifactsClient {
        return (this._artifacts ??= new ArtifactsClient(this._options));
    }

    public get auth(): AuthClient {
        return (this._auth ??= new AuthClient(this._options));
    }

    public get billing(): BillingClient {
        return (this._billing ??= new BillingClient(this._options));
    }

    public get chat(): ChatClient {
        return (this._chat ??= new ChatClient(this._options));
    }

    public get aiAssistant(): AiAssistantClient {
        return (this._aiAssistant ??= new AiAssistantClient(this._options));
    }

    public get compliance(): ComplianceClient {
        return (this._compliance ??= new ComplianceClient(this._options));
    }

    public get events(): EventsClient {
        return (this._events ??= new EventsClient(this._options));
    }

    public get gpu(): GpuClient {
        return (this._gpu ??= new GpuClient(this._options));
    }

    public get infrastructure(): InfrastructureClient {
        return (this._infrastructure ??= new InfrastructureClient(this._options));
    }

    public get hosts(): HostsClient {
        return (this._hosts ??= new HostsClient(this._options));
    }

    public get inference(): InferenceClient {
        return (this._inference ??= new InferenceClient(this._options));
    }

    public get inferenceV2(): InferenceV2Client {
        return (this._inferenceV2 ??= new InferenceV2Client(this._options));
    }

    public get instances(): InstancesClient {
        return (this._instances ??= new InstancesClient(this._options));
    }

    public get jurisdiction(): JurisdictionClient {
        return (this._jurisdiction ??= new JurisdictionClient(this._options));
    }

    public get marketplace(): MarketplaceClient {
        return (this._marketplace ??= new MarketplaceClient(this._options));
    }

    public get marketplaceV2(): MarketplaceV2Client {
        return (this._marketplaceV2 ??= new MarketplaceV2Client(this._options));
    }

    public get mfa(): MfaClient {
        return (this._mfa ??= new MfaClient(this._options));
    }

    public get notifications(): NotificationsClient {
        return (this._notifications ??= new NotificationsClient(this._options));
    }

    public get privacy(): PrivacyClient {
        return (this._privacy ??= new PrivacyClient(this._options));
    }

    public get providers(): ProvidersClient {
        return (this._providers ??= new ProvidersClient(this._options));
    }

    public get reputation(): ReputationClient {
        return (this._reputation ??= new ReputationClient(this._options));
    }

    public get sla(): SlaClient {
        return (this._sla ??= new SlaClient(this._options));
    }

    public get spotPricing(): SpotPricingClient {
        return (this._spotPricing ??= new SpotPricingClient(this._options));
    }

    public get sshKeys(): SshKeysClient {
        return (this._sshKeys ??= new SshKeysClient(this._options));
    }

    public get teams(): TeamsClient {
        return (this._teams ??= new TeamsClient(this._options));
    }

    public get verification(): VerificationClient {
        return (this._verification ??= new VerificationClient(this._options));
    }

    public get volumes(): VolumesClient {
        return (this._volumes ??= new VolumesClient(this._options));
    }

    /**
     * Make a passthrough request using the SDK's configured auth, retry, logging, etc.
     * This is useful for making requests to endpoints not yet supported in the SDK.
     * The input can be a URL string, URL object, or Request object. Relative paths are resolved against the configured base URL.
     *
     * @param {Request | string | URL} input - The URL, path, or Request object.
     * @param {RequestInit} init - Standard fetch RequestInit options.
     * @param {core.PassthroughRequest.RequestOptions} requestOptions - Per-request overrides (timeout, retries, headers, abort signal).
     * @returns {Promise<Response>} A standard Response object.
     */
    public async fetch(
        input: Request | string | URL,
        init?: RequestInit,
        requestOptions?: core.PassthroughRequest.RequestOptions,
    ): Promise<Response> {
        return core.makePassthroughRequest(
            input,
            init,
            {
                baseUrl: this._options.baseUrl ?? this._options.environment,
                headers: this._options.headers,
                timeoutInSeconds: this._options.timeoutInSeconds,
                maxRetries: this._options.maxRetries,
                fetch: this._options.fetch,
                logging: this._options.logging,
            },
            requestOptions,
        );
    }
}
