// This file was auto-generated by Fern from our API Definition.

export const XcelsiorApiEnvironment = {
    Production: "https://xcelsior.ca",
} as const;

export type XcelsiorApiEnvironment = typeof XcelsiorApiEnvironment.Production;
