// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         host_id: "host_id"
 *     }
 */
export interface ApiRemoveHostHostHostIdDeleteRequest {
    host_id: string;
}
