// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         host_id: "host_id",
 *         ip: "ip",
 *         gpu_model: "gpu_model",
 *         total_vram_gb: 1.1,
 *         free_vram_gb: 1.1
 *     }
 */
export interface HostIn {
    host_id: string;
    ip: string;
    gpu_model: string;
    total_vram_gb: number;
    free_vram_gb: number;
    cost_per_hour?: number;
    country?: string;
    province?: string;
    versions?: Record<string, unknown> | null;
    corporation_name?: string;
    business_number?: string;
    gst_hst_number?: string;
    legal_name?: string;
}
